create table car (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	make VARCHAR(50) NOT NULL,
	model VARCHAR(50) NOT NULL,
	price NUMERIC(19,2) NOT NULL
);
insert into car (make, model, price) values ('Jeep', 'Patriot', 25686.87);
insert into car (make, model, price) values ('Jeep', 'Wrangler', 93393.22);
insert into car (make, model, price) values ('Audi', '90', 92709.68);
insert into car (make, model, price) values ('Lexus', 'RX', 84946.73);
insert into car (make, model, price) values ('Ford', 'Explorer', 35005.07);
insert into car (make, model, price) values ('BMW', 'X6 M', 91912.79);
insert into car (make, model, price) values ('Dodge', 'Ramcharger', 63250.07);
insert into car (make, model, price) values ('Ford', 'Edge', 10844.46);
insert into car (make, model, price) values ('Ford', 'F-Series', 89229.82);
insert into car (make, model, price) values ('Lincoln', 'Continental', 78714.46);
insert into car (make, model, price) values ('Mitsubishi', 'Truck', 85049.70);
insert into car (make, model, price) values ('Dodge', 'Caliber', 39032.05);
insert into car (make, model, price) values ('Chevrolet', 'Suburban 1500', 19689.52);
insert into car (make, model, price) values ('Volkswagen', 'Touareg', 79007.42);
insert into car (make, model, price) values ('Toyota', 'Sienna', 48359.59);
insert into car (make, model, price) values ('Eagle', 'Talon', 97842.12);
insert into car (make, model, price) values ('Volvo', 'V50', 75863.71);
insert into car (make, model, price) values ('Suzuki', 'Daewoo Lacetti', 59141.02);
insert into car (make, model, price) values ('Chevrolet', 'Corvette', 17541.84);
insert into car (make, model, price) values ('Hummer', 'H2', 24566.24);
insert into car (make, model, price) values ('Nissan', 'Xterra', 27390.50);
insert into car (make, model, price) values ('Studebaker', 'Avanti', 90240.53);
insert into car (make, model, price) values ('Dodge', 'Stratus', 26675.41);
insert into car (make, model, price) values ('Jaguar', 'XF', 30711.05);
insert into car (make, model, price) values ('Volkswagen', 'Cabriolet', 40127.85);
insert into car (make, model, price) values ('GMC', 'Savana 3500', 90740.98);
insert into car (make, model, price) values ('Chevrolet', 'Corvette', 83431.01);
insert into car (make, model, price) values ('GMC', 'Yukon XL 1500', 93120.60);
insert into car (make, model, price) values ('Mitsubishi', 'Lancer', 98892.44);
insert into car (make, model, price) values ('Toyota', 'Tacoma Xtra', 36531.11);
insert into car (make, model, price) values ('Chevrolet', 'Express 2500', 90640.10);
insert into car (make, model, price) values ('Scion', 'xD', 90319.61);
insert into car (make, model, price) values ('Scion', 'xA', 60648.00);
insert into car (make, model, price) values ('Honda', 'Accord', 20406.43);
insert into car (make, model, price) values ('GMC', 'Savana 1500', 39571.57);
insert into car (make, model, price) values ('GMC', 'Sierra 3500', 86413.76);
insert into car (make, model, price) values ('Toyota', 'Tundra', 51647.37);
insert into car (make, model, price) values ('Oldsmobile', 'Intrigue', 16054.42);
insert into car (make, model, price) values ('Chevrolet', 'Prizm', 41023.75);
insert into car (make, model, price) values ('Lexus', 'SC', 10838.67);
insert into car (make, model, price) values ('Dodge', 'Dakota', 66775.08);
insert into car (make, model, price) values ('Dodge', 'Ram 3500', 72593.61);
insert into car (make, model, price) values ('Audi', 'Cabriolet', 19609.23);
insert into car (make, model, price) values ('Buick', 'LeSabre', 36120.57);
insert into car (make, model, price) values ('Chevrolet', 'Cavalier', 63424.70);
insert into car (make, model, price) values ('Ford', 'F350', 66801.25);
insert into car (make, model, price) values ('Dodge', 'Ram 3500', 55826.00);
insert into car (make, model, price) values ('Pontiac', 'Gemini', 34746.33);
insert into car (make, model, price) values ('Suzuki', 'Forenza', 38983.72);
insert into car (make, model, price) values ('Maserati', 'Spyder', 54908.94);
insert into car (make, model, price) values ('Mazda', 'MPV', 40972.63);
insert into car (make, model, price) values ('Volkswagen', 'Routan', 56767.67);
insert into car (make, model, price) values ('Oldsmobile', 'LSS', 44181.95);
insert into car (make, model, price) values ('Buick', 'LaCrosse', 28409.71);
insert into car (make, model, price) values ('Ford', 'Explorer', 57967.94);
insert into car (make, model, price) values ('Hyundai', 'Santa Fe', 12372.14);
insert into car (make, model, price) values ('Oldsmobile', 'Bravada', 49143.94);
insert into car (make, model, price) values ('Chevrolet', 'Silverado 1500', 88122.54);
insert into car (make, model, price) values ('GMC', '2500 Club Coupe', 65187.70);
insert into car (make, model, price) values ('Acura', 'NSX', 78868.32);
insert into car (make, model, price) values ('Dodge', 'Ram Van 1500', 70029.73);
insert into car (make, model, price) values ('Ford', 'F150', 34880.97);
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', 24400.72);
insert into car (make, model, price) values ('Chevrolet', 'Suburban 1500', 40718.75);
insert into car (make, model, price) values ('GMC', 'Jimmy', 73970.58);
insert into car (make, model, price) values ('Lincoln', 'Continental', 98263.80);
insert into car (make, model, price) values ('Chevrolet', 'Beretta', 62059.92);
insert into car (make, model, price) values ('Chevrolet', 'Express 1500', 76010.53);
insert into car (make, model, price) values ('Ford', 'Aspire', 48631.45);
insert into car (make, model, price) values ('Ford', 'F250', 63337.36);
insert into car (make, model, price) values ('Dodge', 'Ram 1500', 84923.05);
insert into car (make, model, price) values ('Jaguar', 'XJ Series', 93091.11);
insert into car (make, model, price) values ('Mercedes-Benz', 'W201', 11721.74);
insert into car (make, model, price) values ('Bentley', 'Continental GTC', 42640.19);
insert into car (make, model, price) values ('Toyota', 'TundraMax', 50143.26);
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', 83543.43);
insert into car (make, model, price) values ('Pontiac', 'Sunbird', 53616.91);
insert into car (make, model, price) values ('BMW', 'Z3', 86554.56);
insert into car (make, model, price) values ('Land Rover', 'LR2', 41398.86);
insert into car (make, model, price) values ('Acura', 'CL', 75199.87);
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', 71405.70);
insert into car (make, model, price) values ('Hyundai', 'Elantra', 37058.08);
insert into car (make, model, price) values ('Chevrolet', 'Suburban 2500', 98904.26);
insert into car (make, model, price) values ('Mazda', 'MPV', 92938.89);
insert into car (make, model, price) values ('Volkswagen', 'Phaeton', 40066.46);
insert into car (make, model, price) values ('Audi', 'S6', 28516.94);
insert into car (make, model, price) values ('Jaguar', 'S-Type', 35664.61);
insert into car (make, model, price) values ('Ford', 'Econoline E150', 70043.58);
insert into car (make, model, price) values ('Toyota', 'Celica', 70762.73);
insert into car (make, model, price) values ('Dodge', 'D350 Club', 49680.19);
insert into car (make, model, price) values ('Scion', 'tC', 13533.26);
insert into car (make, model, price) values ('Chevrolet', 'Aveo', 35652.26);
insert into car (make, model, price) values ('Chevrolet', 'Sportvan G10', 82076.41);
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', 62312.65);
insert into car (make, model, price) values ('Ford', 'Escort', 30130.64);
insert into car (make, model, price) values ('Ford', 'Escort', 74763.03);
insert into car (make, model, price) values ('Chevrolet', 'Express 1500', 37911.69);
insert into car (make, model, price) values ('Porsche', '911', 12558.97);
insert into car (make, model, price) values ('Acura', 'TL', 58124.21);
insert into car (make, model, price) values ('Volvo', '740', 58280.78);
insert into car (make, model, price) values ('Buick', 'Regal', 20659.97);
insert into car (make, model, price) values ('Ford', 'Thunderbird', 61935.25);
insert into car (make, model, price) values ('BMW', '5 Series', 41180.73);
insert into car (make, model, price) values ('GMC', 'Rally Wagon 3500', 75375.91);
insert into car (make, model, price) values ('Isuzu', 'i-Series', 57803.43);
insert into car (make, model, price) values ('Buick', 'Terraza', 47909.79);
insert into car (make, model, price) values ('Hummer', 'H1', 89453.75);
insert into car (make, model, price) values ('Porsche', 'Panamera', 64618.03);
insert into car (make, model, price) values ('Ford', 'Thunderbird', 67256.43);
insert into car (make, model, price) values ('Pontiac', 'Grand Am', 10234.27);
insert into car (make, model, price) values ('Cadillac', 'SRX', 12942.23);
insert into car (make, model, price) values ('Ford', 'Freestar', 67171.66);
insert into car (make, model, price) values ('Dodge', 'Viper', 11297.15);
insert into car (make, model, price) values ('Ford', 'F250', 36493.69);
insert into car (make, model, price) values ('Audi', 'TT', 88275.81);
insert into car (make, model, price) values ('Subaru', 'Outback', 30424.75);
insert into car (make, model, price) values ('Ford', 'Tempo', 17257.54);
insert into car (make, model, price) values ('Infiniti', 'J', 81686.37);
insert into car (make, model, price) values ('Ford', 'Explorer', 29206.78);
insert into car (make, model, price) values ('Chevrolet', 'Malibu', 40867.99);
insert into car (make, model, price) values ('Dodge', 'Ram', 43100.54);
insert into car (make, model, price) values ('Saab', '900', 47467.17);
insert into car (make, model, price) values ('Hyundai', 'Accent', 26264.05);
insert into car (make, model, price) values ('Mercury', 'Cougar', 28082.74);
insert into car (make, model, price) values ('Mercury', 'Cougar', 54330.10);
insert into car (make, model, price) values ('Dodge', 'Dakota', 39881.68);
insert into car (make, model, price) values ('Ford', 'LTD Crown Victoria', 90917.20);
insert into car (make, model, price) values ('Chevrolet', 'Aveo', 84593.21);
insert into car (make, model, price) values ('Toyota', 'Camry', 71202.25);
insert into car (make, model, price) values ('Buick', 'Riviera', 95112.43);
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', 63912.23);
insert into car (make, model, price) values ('Suzuki', 'Reno', 32223.14);
insert into car (make, model, price) values ('Pontiac', 'Firebird', 44029.21);
insert into car (make, model, price) values ('Pontiac', 'Sunbird', 30564.34);
insert into car (make, model, price) values ('Chevrolet', 'Venture', 90489.63);
insert into car (make, model, price) values ('Land Rover', 'Range Rover', 94736.33);
insert into car (make, model, price) values ('Pontiac', 'Grand Am', 28673.05);
insert into car (make, model, price) values ('Mitsubishi', 'Eclipse', 29684.62);
insert into car (make, model, price) values ('Geo', 'Storm', 14330.32);
insert into car (make, model, price) values ('Dodge', 'Caliber', 94777.61);
insert into car (make, model, price) values ('Buick', 'Riviera', 90635.69);
insert into car (make, model, price) values ('Kia', 'Rio', 20679.54);
insert into car (make, model, price) values ('Suzuki', 'X-90', 62455.36);
insert into car (make, model, price) values ('Ford', 'Explorer', 44904.01);
insert into car (make, model, price) values ('Subaru', 'B9 Tribeca', 57961.03);
insert into car (make, model, price) values ('Subaru', 'Legacy', 96734.10);
insert into car (make, model, price) values ('Chevrolet', 'Lumina', 73305.40);
insert into car (make, model, price) values ('Toyota', 'Celica', 34933.56);
insert into car (make, model, price) values ('Mercedes-Benz', '500SEL', 63339.57);
insert into car (make, model, price) values ('Oldsmobile', '98', 15723.71);
insert into car (make, model, price) values ('GMC', 'Yukon', 19423.01);
insert into car (make, model, price) values ('Eagle', 'Vision', 88863.75);
insert into car (make, model, price) values ('Mercedes-Benz', 'R-Class', 65453.09);
insert into car (make, model, price) values ('Pontiac', 'Gemini', 70350.79);
insert into car (make, model, price) values ('Kia', 'Rondo', 10416.83);
insert into car (make, model, price) values ('Dodge', 'Neon', 65409.62);
insert into car (make, model, price) values ('Kia', 'Sedona', 48340.29);
insert into car (make, model, price) values ('Pontiac', '6000', 44328.34);
insert into car (make, model, price) values ('Mercedes-Benz', 'M-Class', 98658.05);
insert into car (make, model, price) values ('Suzuki', 'XL7', 90347.31);
insert into car (make, model, price) values ('Chevrolet', 'Corsica', 91979.18);
insert into car (make, model, price) values ('Mercury', 'Tracer', 79108.84);
insert into car (make, model, price) values ('Nissan', 'Murano', 91023.49);
insert into car (make, model, price) values ('Land Rover', 'Range Rover', 90594.18);
insert into car (make, model, price) values ('Chevrolet', 'Express 1500', 36219.07);
insert into car (make, model, price) values ('Volvo', 'S60', 90872.88);
insert into car (make, model, price) values ('Toyota', 'Tacoma Xtra', 39761.12);
insert into car (make, model, price) values ('Subaru', 'Legacy', 79344.22);
insert into car (make, model, price) values ('Ford', 'Econoline E250', 26431.99);
insert into car (make, model, price) values ('Pontiac', '6000', 66502.97);
insert into car (make, model, price) values ('Lexus', 'LS', 96851.28);
insert into car (make, model, price) values ('Chevrolet', '2500', 79334.38);
insert into car (make, model, price) values ('Scion', 'xD', 75213.11);
insert into car (make, model, price) values ('Chrysler', 'PT Cruiser', 33575.65);
insert into car (make, model, price) values ('Nissan', 'Maxima', 77509.96);
insert into car (make, model, price) values ('Ford', 'Ranger', 91793.01);
insert into car (make, model, price) values ('BMW', 'X6', 41994.25);
insert into car (make, model, price) values ('Audi', 'A8', 31579.58);
insert into car (make, model, price) values ('Mitsubishi', 'Chariot', 77739.08);
insert into car (make, model, price) values ('Mazda', '626', 69154.86);
insert into car (make, model, price) values ('Dodge', 'Journey', 46855.04);
insert into car (make, model, price) values ('Kia', 'Sedona', 81053.33);
insert into car (make, model, price) values ('BMW', 'Z4', 56902.47);
insert into car (make, model, price) values ('Ferrari', 'FF', 31780.45);
insert into car (make, model, price) values ('Infiniti', 'I', 95808.39);
insert into car (make, model, price) values ('Dodge', 'Viper', 38802.92);
insert into car (make, model, price) values ('Volvo', 'S40', 43151.28);
insert into car (make, model, price) values ('Subaru', 'Legacy', 88432.89);
insert into car (make, model, price) values ('Chevrolet', 'Suburban', 52489.97);
insert into car (make, model, price) values ('Toyota', '4Runner', 82539.54);
insert into car (make, model, price) values ('Lexus', 'IS', 53877.11);
insert into car (make, model, price) values ('Toyota', '4Runner', 69732.94);
insert into car (make, model, price) values ('Toyota', 'Solara', 55241.83);
insert into car (make, model, price) values ('Nissan', '240SX', 35105.51);
insert into car (make, model, price) values ('Chevrolet', 'Silverado 2500', 75933.31);
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', 32365.44);
insert into car (make, model, price) values ('Acura', 'CL', 83303.27);
insert into car (make, model, price) values ('Nissan', 'Xterra', 42412.47);
insert into car (make, model, price) values ('Chrysler', 'Sebring', 73597.31);
insert into car (make, model, price) values ('Chrysler', '300M', 85483.38);
insert into car (make, model, price) values ('Nissan', 'Murano', 41793.51);
insert into car (make, model, price) values ('Cadillac', 'SRX', 72142.03);
insert into car (make, model, price) values ('Ford', 'Ranger', 77063.55);
insert into car (make, model, price) values ('Oldsmobile', 'Silhouette', 29671.16);
insert into car (make, model, price) values ('Volvo', 'S60', 53687.97);
insert into car (make, model, price) values ('Ford', 'Freestar', 32167.40);
insert into car (make, model, price) values ('Audi', '90', 58139.60);
insert into car (make, model, price) values ('Chrysler', '300', 20414.87);
insert into car (make, model, price) values ('Jaguar', 'X-Type', 87793.22);
insert into car (make, model, price) values ('Ford', 'Transit Connect', 15142.09);
insert into car (make, model, price) values ('Mazda', 'CX-7', 74126.38);
insert into car (make, model, price) values ('Mazda', 'Mazda6', 71673.59);
insert into car (make, model, price) values ('Mercury', 'Cougar', 84993.88);
insert into car (make, model, price) values ('Aston Martin', 'DBS', 10955.58);
insert into car (make, model, price) values ('Acura', 'TL', 65009.37);
insert into car (make, model, price) values ('Chevrolet', 'Suburban 1500', 48289.90);
insert into car (make, model, price) values ('Honda', 'Insight', 14928.22);
insert into car (make, model, price) values ('Infiniti', 'FX', 76839.84);
insert into car (make, model, price) values ('Mercedes-Benz', 'SLS-Class', 70130.78);
insert into car (make, model, price) values ('Buick', 'Riviera', 60727.59);
insert into car (make, model, price) values ('Ford', 'Festiva', 15932.03);
insert into car (make, model, price) values ('Plymouth', 'Neon', 94176.82);
insert into car (make, model, price) values ('Mitsubishi', 'Tredia', 10597.00);
insert into car (make, model, price) values ('GMC', 'Savana 2500', 27426.22);
insert into car (make, model, price) values ('Cadillac', 'Catera', 68045.82);
insert into car (make, model, price) values ('Mitsubishi', 'GTO', 77247.74);
insert into car (make, model, price) values ('Smart', 'Fortwo', 57434.37);
insert into car (make, model, price) values ('Porsche', 'Carrera GT', 51625.13);
insert into car (make, model, price) values ('Ford', 'Econoline E350', 19994.31);
insert into car (make, model, price) values ('Chrysler', 'Town & Country', 77820.53);
insert into car (make, model, price) values ('Chevrolet', 'Astro', 10666.89);
insert into car (make, model, price) values ('GMC', '1500', 67598.96);
insert into car (make, model, price) values ('Ford', 'Mustang', 91397.27);
insert into car (make, model, price) values ('Buick', 'Park Avenue', 91980.35);
insert into car (make, model, price) values ('Plymouth', 'Laser', 97393.25);
insert into car (make, model, price) values ('Pontiac', 'Vibe', 20354.21);
insert into car (make, model, price) values ('Maserati', 'Gran Sport', 56782.76);
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', 14707.31);
insert into car (make, model, price) values ('Nissan', 'Pathfinder', 77861.92);
insert into car (make, model, price) values ('Acura', 'NSX', 10156.27);
insert into car (make, model, price) values ('Volkswagen', 'Jetta III', 20647.65);
insert into car (make, model, price) values ('Mazda', 'Millenia', 85106.74);
insert into car (make, model, price) values ('Ford', 'Galaxie', 59073.78);
insert into car (make, model, price) values ('Volkswagen', 'GTI', 35991.44);
insert into car (make, model, price) values ('Lamborghini', 'Gallardo', 68200.44);
insert into car (make, model, price) values ('Infiniti', 'J', 76521.70);
insert into car (make, model, price) values ('Mazda', '929', 36553.44);
insert into car (make, model, price) values ('Alfa Romeo', 'Spider', 22389.91);
insert into car (make, model, price) values ('Mercedes-Benz', 'SLS AMG', 10209.37);
insert into car (make, model, price) values ('Ford', 'Escort', 37482.73);
insert into car (make, model, price) values ('Chrysler', 'Cirrus', 45338.41);
insert into car (make, model, price) values ('Pontiac', 'Grand Am', 74817.78);
insert into car (make, model, price) values ('Pontiac', '1000', 18023.92);
insert into car (make, model, price) values ('GMC', 'Suburban 2500', 30033.38);
insert into car (make, model, price) values ('Toyota', 'Camry', 60466.94);
insert into car (make, model, price) values ('Suzuki', 'Samurai', 20683.70);
insert into car (make, model, price) values ('Buick', 'Regal', 11079.27);
insert into car (make, model, price) values ('Ford', 'F450', 16245.60);
insert into car (make, model, price) values ('GMC', 'Sierra 2500', 57743.94);
insert into car (make, model, price) values ('Ford', 'Expedition', 93537.06);
insert into car (make, model, price) values ('Volkswagen', 'Rabbit', 40816.03);
insert into car (make, model, price) values ('Volkswagen', 'Tiguan', 59419.98);
insert into car (make, model, price) values ('Pontiac', 'Bonneville', 44869.61);
insert into car (make, model, price) values ('Volkswagen', 'rio', 48309.98);
insert into car (make, model, price) values ('Ford', 'Escape', 79712.56);
insert into car (make, model, price) values ('Hyundai', 'Santa Fe', 51928.59);
insert into car (make, model, price) values ('Dodge', 'Dakota Club', 44022.82);
insert into car (make, model, price) values ('Acura', 'RDX', 82730.01);
insert into car (make, model, price) values ('Audi', 'Cabriolet', 97207.02);
insert into car (make, model, price) values ('Chevrolet', 'Tahoe', 71386.81);
insert into car (make, model, price) values ('BMW', '760', 76171.38);
insert into car (make, model, price) values ('Chrysler', 'Pacifica', 74440.58);
insert into car (make, model, price) values ('Ford', 'F-Series', 72870.57);
insert into car (make, model, price) values ('Kia', 'Rondo', 73712.21);
insert into car (make, model, price) values ('Chevrolet', 'Avalanche 1500', 80459.27);
insert into car (make, model, price) values ('Daewoo', 'Nubira', 46190.20);
insert into car (make, model, price) values ('Isuzu', 'i-290', 67671.75);
insert into car (make, model, price) values ('Chevrolet', 'Tracker', 48038.53);
insert into car (make, model, price) values ('Audi', '80', 62689.78);
insert into car (make, model, price) values ('Aptera', '2e', 81241.48);
insert into car (make, model, price) values ('Pontiac', 'Fiero', 64113.21);
insert into car (make, model, price) values ('BMW', '5 Series', 58610.76);
insert into car (make, model, price) values ('Ford', 'Freestyle', 16203.72);
insert into car (make, model, price) values ('Mazda', 'MPV', 86566.16);
insert into car (make, model, price) values ('Nissan', 'Maxima', 61247.51);
insert into car (make, model, price) values ('Nissan', 'Xterra', 14714.05);
insert into car (make, model, price) values ('Chevrolet', 'Avalanche 1500', 74255.20);
insert into car (make, model, price) values ('Mitsubishi', '3000GT', 66843.63);
insert into car (make, model, price) values ('Lincoln', 'Navigator L', 22441.72);
insert into car (make, model, price) values ('Mercury', 'Tracer', 91190.84);
insert into car (make, model, price) values ('Dodge', 'Ram 2500', 63654.36);
insert into car (make, model, price) values ('Mitsubishi', 'Galant', 34214.66);
insert into car (make, model, price) values ('Pontiac', 'Trans Sport', 42915.31);
insert into car (make, model, price) values ('GMC', 'Jimmy', 53668.07);
insert into car (make, model, price) values ('Pontiac', 'Bonneville', 26647.62);
insert into car (make, model, price) values ('Mitsubishi', 'Eclipse', 79085.46);
insert into car (make, model, price) values ('Nissan', 'NV1500', 72410.96);
insert into car (make, model, price) values ('Dodge', 'Dakota Club', 28378.89);
insert into car (make, model, price) values ('Toyota', 'RAV4', 16790.08);
insert into car (make, model, price) values ('Morgan', 'Aero 8', 57401.48);
insert into car (make, model, price) values ('Mercedes-Benz', 'SLK-Class', 74286.01);
insert into car (make, model, price) values ('Pontiac', 'Bonneville', 35047.30);
insert into car (make, model, price) values ('Hyundai', 'Accent', 23169.73);
insert into car (make, model, price) values ('Ford', 'Courier', 74924.72);
insert into car (make, model, price) values ('Volvo', 'XC60', 50142.70);
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', 87617.54);
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', 24048.16);
insert into car (make, model, price) values ('Chevrolet', 'Silverado 1500', 93342.36);
insert into car (make, model, price) values ('Cadillac', 'Seville', 38844.96);
insert into car (make, model, price) values ('Jeep', 'Wrangler', 24733.98);
insert into car (make, model, price) values ('Chevrolet', '1500', 12034.84);
insert into car (make, model, price) values ('GMC', 'Sonoma Club Coupe', 99772.85);
insert into car (make, model, price) values ('Lexus', 'SC', 41079.83);
insert into car (make, model, price) values ('Lotus', 'Exige', 17840.96);
insert into car (make, model, price) values ('Austin', 'Mini Cooper', 17090.24);
insert into car (make, model, price) values ('Honda', 'Accord', 94596.31);
insert into car (make, model, price) values ('Plymouth', 'Colt', 72747.68);
insert into car (make, model, price) values ('Pontiac', 'Sunfire', 47390.00);
insert into car (make, model, price) values ('Dodge', 'Ram 1500', 61349.18);
insert into car (make, model, price) values ('Geo', 'Metro', 60009.22);
insert into car (make, model, price) values ('Porsche', '928', 56284.20);
insert into car (make, model, price) values ('Hyundai', 'Sonata', 17846.21);
insert into car (make, model, price) values ('Isuzu', 'i-370', 91036.18);
insert into car (make, model, price) values ('Dodge', 'Dynasty', 28954.67);
insert into car (make, model, price) values ('Audi', 'A6', 27115.56);
insert into car (make, model, price) values ('Kia', 'Borrego', 55644.26);
insert into car (make, model, price) values ('Infiniti', 'FX', 68922.84);
insert into car (make, model, price) values ('Bentley', 'Continental', 11087.15);
insert into car (make, model, price) values ('BMW', 'X6 M', 35123.19);
insert into car (make, model, price) values ('Volkswagen', 'Golf', 47093.64);
insert into car (make, model, price) values ('Subaru', 'Justy', 16570.71);
insert into car (make, model, price) values ('Dodge', 'Ram Van 2500', 38704.49);
insert into car (make, model, price) values ('Acura', 'NSX', 45382.60);
insert into car (make, model, price) values ('Land Rover', 'Freelander', 92955.08);
insert into car (make, model, price) values ('Hyundai', 'Sonata', 97133.70);
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', 49078.93);
insert into car (make, model, price) values ('Suzuki', 'Verona', 10674.37);
insert into car (make, model, price) values ('Jaguar', 'XJ', 34579.21);
insert into car (make, model, price) values ('Chevrolet', 'Colorado', 51894.46);
insert into car (make, model, price) values ('Ford', 'Expedition', 15059.15);
insert into car (make, model, price) values ('Toyota', 'Tacoma', 73792.28);
insert into car (make, model, price) values ('GMC', 'Savana 3500', 86484.39);
insert into car (make, model, price) values ('Subaru', 'Impreza', 24026.03);
insert into car (make, model, price) values ('Kia', 'Optima', 11650.57);
insert into car (make, model, price) values ('Chevrolet', 'Camaro', 59097.26);
insert into car (make, model, price) values ('Mazda', 'Millenia', 16096.42);
insert into car (make, model, price) values ('Audi', 'Coupe GT', 70375.06);
insert into car (make, model, price) values ('GMC', 'Suburban 1500', 43883.11);
insert into car (make, model, price) values ('Plymouth', 'Sundance', 21182.98);
insert into car (make, model, price) values ('Porsche', 'Cayenne', 61103.03);
insert into car (make, model, price) values ('Chevrolet', 'Astro', 63797.11);
insert into car (make, model, price) values ('Pontiac', 'Vibe', 51407.85);
insert into car (make, model, price) values ('Dodge', 'Ram 1500 Club', 63094.22);
insert into car (make, model, price) values ('Chrysler', 'Imperial', 69846.73);
insert into car (make, model, price) values ('Hyundai', 'Accent', 77221.17);
insert into car (make, model, price) values ('Volkswagen', 'GTI', 90604.63);
insert into car (make, model, price) values ('Chrysler', 'Sebring', 53829.77);
insert into car (make, model, price) values ('Honda', 'Civic', 78226.74);
insert into car (make, model, price) values ('Chevrolet', 'Cobalt', 68520.49);
insert into car (make, model, price) values ('GMC', 'Yukon', 89479.14);
insert into car (make, model, price) values ('Jaguar', 'S-Type', 23699.63);
insert into car (make, model, price) values ('Ferrari', 'F430', 67351.43);
insert into car (make, model, price) values ('Suzuki', 'Vitara', 17707.22);
insert into car (make, model, price) values ('Buick', 'Riviera', 41710.51);
insert into car (make, model, price) values ('Volkswagen', 'GTI', 57964.63);
insert into car (make, model, price) values ('Mercedes-Benz', 'W201', 53480.43);
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', 14586.62);
insert into car (make, model, price) values ('Chevrolet', 'Express 1500', 98722.25);
insert into car (make, model, price) values ('Ford', 'Edge', 92694.87);
insert into car (make, model, price) values ('BMW', '6 Series', 61803.71);
insert into car (make, model, price) values ('Chevrolet', 'Monte Carlo', 92263.11);
insert into car (make, model, price) values ('Cadillac', 'STS-V', 46515.87);
insert into car (make, model, price) values ('Hummer', 'H3T', 89072.38);
insert into car (make, model, price) values ('Mazda', 'Mazda3', 65262.58);
insert into car (make, model, price) values ('Chevrolet', 'Corvette', 70118.99);
insert into car (make, model, price) values ('Mitsubishi', 'Lancer Evolution', 72569.44);
insert into car (make, model, price) values ('Volkswagen', 'New Beetle', 21066.94);
insert into car (make, model, price) values ('Toyota', 'Cressida', 20358.22);
insert into car (make, model, price) values ('Isuzu', 'Ascender', 83097.71);
insert into car (make, model, price) values ('Volkswagen', 'Golf', 83263.99);
insert into car (make, model, price) values ('GMC', '3500', 83061.53);
insert into car (make, model, price) values ('Land Rover', 'LR3', 26691.56);
insert into car (make, model, price) values ('BMW', '5 Series', 26191.45);
insert into car (make, model, price) values ('Ford', 'Windstar', 10931.05);
insert into car (make, model, price) values ('Isuzu', 'Impulse', 73150.42);
insert into car (make, model, price) values ('Lincoln', 'Continental Mark VII', 68646.49);
insert into car (make, model, price) values ('Ford', 'Focus', 40504.87);
insert into car (make, model, price) values ('Volvo', 'XC90', 75742.70);
insert into car (make, model, price) values ('Nissan', 'Titan', 62683.07);
insert into car (make, model, price) values ('Mazda', 'RX-8', 41884.25);
insert into car (make, model, price) values ('Oldsmobile', 'Intrigue', 95277.61);
insert into car (make, model, price) values ('Toyota', 'Celica', 23569.91);
insert into car (make, model, price) values ('Porsche', 'Cayenne', 34615.41);
insert into car (make, model, price) values ('Mazda', 'Protege', 17137.90);
insert into car (make, model, price) values ('Buick', 'Rendezvous', 61871.31);
insert into car (make, model, price) values ('Volvo', 'XC70', 91357.29);
insert into car (make, model, price) values ('Toyota', 'Tundra', 86493.85);
insert into car (make, model, price) values ('Hummer', 'H2', 49645.33);
insert into car (make, model, price) values ('Chevrolet', 'G-Series G30', 74522.55);
insert into car (make, model, price) values ('Lamborghini', 'Reventón', 47191.84);
insert into car (make, model, price) values ('Dodge', 'Ram Van 3500', 57818.12);
insert into car (make, model, price) values ('Kia', 'Optima', 78882.11);
insert into car (make, model, price) values ('Pontiac', 'G6', 98788.11);
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', 43358.25);
insert into car (make, model, price) values ('Suzuki', 'Equator', 87355.14);
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', 87645.34);
insert into car (make, model, price) values ('Ford', 'Escort', 23344.33);
insert into car (make, model, price) values ('Mercury', 'Mountaineer', 95190.82);
insert into car (make, model, price) values ('Mercury', 'Mountaineer', 44745.32);
insert into car (make, model, price) values ('Ford', 'Expedition', 45253.46);
insert into car (make, model, price) values ('Aston Martin', 'DBS', 36656.86);
insert into car (make, model, price) values ('Buick', 'Skylark', 80626.41);
insert into car (make, model, price) values ('Lincoln', 'MKX', 46592.43);
insert into car (make, model, price) values ('Chevrolet', 'Impala', 14334.64);
insert into car (make, model, price) values ('Volvo', 'S40', 34194.18);
insert into car (make, model, price) values ('Pontiac', 'Solstice', 94138.67);
insert into car (make, model, price) values ('Dodge', 'Sprinter', 57511.94);
insert into car (make, model, price) values ('BMW', '7 Series', 74431.24);
insert into car (make, model, price) values ('Mitsubishi', 'Mirage', 11349.90);
insert into car (make, model, price) values ('GMC', 'Yukon XL 1500', 51252.13);
insert into car (make, model, price) values ('Acura', 'RDX', 99217.83);
insert into car (make, model, price) values ('GMC', 'Sonoma', 53386.96);
insert into car (make, model, price) values ('Buick', 'Reatta', 81568.55);
insert into car (make, model, price) values ('Cadillac', 'STS', 73023.89);
insert into car (make, model, price) values ('Ford', 'Freestyle', 12212.35);
insert into car (make, model, price) values ('Mercury', 'Cougar', 81712.24);
insert into car (make, model, price) values ('Saturn', 'S-Series', 25994.39);
insert into car (make, model, price) values ('Audi', 'riolet', 87115.17);
insert into car (make, model, price) values ('GMC', 'Sierra 2500HD', 22852.23);
insert into car (make, model, price) values ('Toyota', '4Runner', 62865.54);
insert into car (make, model, price) values ('Mercedes-Benz', 'R-Class', 21821.89);
insert into car (make, model, price) values ('Toyota', 'Land Cruiser', 96353.44);
insert into car (make, model, price) values ('Mazda', 'Tribute', 59182.00);
insert into car (make, model, price) values ('Mitsubishi', 'L300', 97227.53);
insert into car (make, model, price) values ('Chevrolet', 'Express 2500', 87190.34);
insert into car (make, model, price) values ('Mercedes-Benz', 'SLK-Class', 50682.65);
insert into car (make, model, price) values ('Chevrolet', 'Monte Carlo', 35509.91);
insert into car (make, model, price) values ('Mazda', 'Mazda3', 39465.80);
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', 13056.08);
insert into car (make, model, price) values ('Ford', 'Explorer', 71323.50);
insert into car (make, model, price) values ('Suzuki', 'SJ', 91287.77);
insert into car (make, model, price) values ('Hyundai', 'Azera', 84327.60);
insert into car (make, model, price) values ('Volkswagen', 'Passat', 40411.28);
insert into car (make, model, price) values ('Toyota', 'MR2', 93542.42);
insert into car (make, model, price) values ('Suzuki', 'Sidekick', 35694.67);
insert into car (make, model, price) values ('Honda', 'Prelude', 52661.60);
insert into car (make, model, price) values ('Volvo', 'S80', 70153.50);
insert into car (make, model, price) values ('Chevrolet', 'Silverado 1500', 93213.21);
insert into car (make, model, price) values ('Mitsubishi', 'Truck', 18984.23);
insert into car (make, model, price) values ('Chevrolet', 'Venture', 20176.79);
insert into car (make, model, price) values ('Ford', 'GT500', 32991.79);
insert into car (make, model, price) values ('Ford', 'Mustang', 10432.20);
insert into car (make, model, price) values ('Lexus', 'RX Hybrid', 98205.82);
insert into car (make, model, price) values ('Chrysler', 'Town & Country', 20040.29);
insert into car (make, model, price) values ('Ford', 'Aerostar', 65199.51);
insert into car (make, model, price) values ('Honda', 'CR-Z', 18222.42);
insert into car (make, model, price) values ('Pontiac', 'Sunbird', 74735.88);
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', 55673.40);
insert into car (make, model, price) values ('Mazda', '929', 29594.38);
insert into car (make, model, price) values ('Chrysler', 'Sebring', 44497.90);
insert into car (make, model, price) values ('Lexus', 'LS', 37313.94);
insert into car (make, model, price) values ('Ford', 'Ranger', 19891.13);
insert into car (make, model, price) values ('Lincoln', 'MKZ', 82958.65);
insert into car (make, model, price) values ('Volvo', 'C30', 16266.27);
insert into car (make, model, price) values ('Pontiac', 'LeMans', 70080.13);
insert into car (make, model, price) values ('Mazda', 'Millenia', 53612.55);
insert into car (make, model, price) values ('Honda', 'Odyssey', 71471.53);
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', 85642.97);
insert into car (make, model, price) values ('Infiniti', 'EX', 45360.94);
insert into car (make, model, price) values ('Chevrolet', 'Tahoe', 45039.22);
insert into car (make, model, price) values ('Mitsubishi', 'Galant', 63741.75);
insert into car (make, model, price) values ('Mazda', 'Mazda6', 94308.39);
insert into car (make, model, price) values ('Mercury', 'Sable', 97536.07);
insert into car (make, model, price) values ('Spyker', 'C8', 33591.83);
insert into car (make, model, price) values ('Ford', 'EXP', 58824.84);
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', 77777.91);
insert into car (make, model, price) values ('Lexus', 'ES', 36412.87);
insert into car (make, model, price) values ('Subaru', 'Justy', 17281.14);
insert into car (make, model, price) values ('Nissan', 'Titan', 97016.82);
insert into car (make, model, price) values ('Mercury', 'Marauder', 99082.97);
insert into car (make, model, price) values ('Nissan', 'Altima', 11938.95);
insert into car (make, model, price) values ('Chevrolet', 'S10', 17322.08);
insert into car (make, model, price) values ('Pontiac', 'Firebird', 18069.98);
insert into car (make, model, price) values ('Audi', 'S5', 77144.97);
insert into car (make, model, price) values ('Chevrolet', 'Corvette', 89405.20);
insert into car (make, model, price) values ('Oldsmobile', 'Bravada', 14293.66);
insert into car (make, model, price) values ('BMW', 'M6', 57940.95);
insert into car (make, model, price) values ('Lexus', 'LS', 45727.03);
insert into car (make, model, price) values ('Nissan', 'Murano', 75094.38);
insert into car (make, model, price) values ('Buick', 'Somerset', 84247.38);
insert into car (make, model, price) values ('Maserati', 'Quattroporte', 52154.30);
insert into car (make, model, price) values ('Toyota', 'Sienna', 82475.34);
insert into car (make, model, price) values ('Mercury', 'Villager', 68971.77);
insert into car (make, model, price) values ('Chevrolet', 'S10', 68642.15);
insert into car (make, model, price) values ('Chevrolet', '3500', 94956.70);
insert into car (make, model, price) values ('Ford', 'Bronco', 43287.77);
insert into car (make, model, price) values ('Mazda', 'Mazda6', 40307.93);
insert into car (make, model, price) values ('Infiniti', 'QX', 37394.04);
insert into car (make, model, price) values ('Peugeot', '207', 39430.97);
insert into car (make, model, price) values ('Kia', 'Rio', 92365.99);
insert into car (make, model, price) values ('Ford', 'F350', 14605.72);
insert into car (make, model, price) values ('GMC', 'Jimmy', 47959.41);
insert into car (make, model, price) values ('Porsche', 'Carrera GT', 56122.28);
insert into car (make, model, price) values ('Aston Martin', 'V8 Vantage S', 75992.65);
insert into car (make, model, price) values ('Pontiac', 'Fiero', 65237.09);
insert into car (make, model, price) values ('Toyota', 'Sienna', 77926.78);
insert into car (make, model, price) values ('Chrysler', '200', 60065.59);
insert into car (make, model, price) values ('Infiniti', 'I', 87652.54);
insert into car (make, model, price) values ('Land Rover', 'Discovery', 62086.24);
insert into car (make, model, price) values ('GMC', 'Vandura 1500', 74357.56);
insert into car (make, model, price) values ('Acura', 'TSX', 60722.59);
insert into car (make, model, price) values ('Dodge', 'Shadow', 16864.47);
insert into car (make, model, price) values ('Toyota', 'Camry', 20371.28);
insert into car (make, model, price) values ('Lincoln', 'Navigator', 52840.53);
insert into car (make, model, price) values ('Nissan', 'Quest', 67749.78);
insert into car (make, model, price) values ('Land Rover', 'Range Rover Sport', 80108.78);
insert into car (make, model, price) values ('Infiniti', 'G', 26375.65);
insert into car (make, model, price) values ('Toyota', 'Supra', 97253.05);
insert into car (make, model, price) values ('Acura', 'TSX', 35434.48);
insert into car (make, model, price) values ('Hyundai', 'Santa Fe', 73191.46);
insert into car (make, model, price) values ('GMC', 'Vandura G2500', 98600.72);
insert into car (make, model, price) values ('Pontiac', 'Trans Sport', 60106.22);
insert into car (make, model, price) values ('Ford', 'E250', 86225.54);
insert into car (make, model, price) values ('Lotus', 'Exige', 85798.69);
insert into car (make, model, price) values ('Land Rover', 'Discovery', 15228.93);
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', 35322.45);
insert into car (make, model, price) values ('Honda', 'Civic', 63107.97);
insert into car (make, model, price) values ('Ford', 'Taurus', 45396.32);
insert into car (make, model, price) values ('Lincoln', 'Navigator', 30071.73);
insert into car (make, model, price) values ('Volkswagen', 'Passat', 10042.79);
insert into car (make, model, price) values ('Chevrolet', 'Corvette', 13737.06);
insert into car (make, model, price) values ('Volkswagen', 'rio', 25893.80);
insert into car (make, model, price) values ('Chevrolet', 'Astro', 24719.06);
insert into car (make, model, price) values ('Audi', '90', 26823.96);
insert into car (make, model, price) values ('Toyota', 'Truck Xtracab SR5', 64396.31);
insert into car (make, model, price) values ('GMC', 'Sierra 3500', 94990.29);
insert into car (make, model, price) values ('Chevrolet', 'Express 3500', 54720.13);
insert into car (make, model, price) values ('Chevrolet', 'Express 3500', 39961.19);
insert into car (make, model, price) values ('BMW', '530', 15405.87);
insert into car (make, model, price) values ('Ford', 'Econoline E250', 94213.89);
insert into car (make, model, price) values ('Ford', 'Taurus', 48523.36);
insert into car (make, model, price) values ('Kia', 'Spectra', 55184.96);
insert into car (make, model, price) values ('Isuzu', 'Amigo', 48074.23);
insert into car (make, model, price) values ('Mitsubishi', 'GTO', 97269.85);
insert into car (make, model, price) values ('Hyundai', 'Sonata', 84809.13);
insert into car (make, model, price) values ('Chevrolet', 'TrailBlazer', 19999.37);
insert into car (make, model, price) values ('Ford', 'Bronco', 87046.86);
insert into car (make, model, price) values ('Chevrolet', 'Cavalier', 83277.89);
insert into car (make, model, price) values ('Ford', 'Econoline E350', 54630.91);
insert into car (make, model, price) values ('GMC', 'Sierra 2500', 24519.08);
insert into car (make, model, price) values ('BMW', 'X5', 55776.16);
insert into car (make, model, price) values ('Mazda', '323', 48820.54);
insert into car (make, model, price) values ('Mercury', 'Cougar', 70033.28);
insert into car (make, model, price) values ('Chevrolet', 'Silverado 2500', 30505.70);
insert into car (make, model, price) values ('BMW', '600', 15586.11);
insert into car (make, model, price) values ('Audi', 'A8', 94314.80);
insert into car (make, model, price) values ('Volvo', 'XC90', 57132.08);
insert into car (make, model, price) values ('Ford', 'Expedition', 20365.34);
insert into car (make, model, price) values ('Honda', 'Civic', 66266.72);
insert into car (make, model, price) values ('Kia', 'Sephia', 95339.19);
insert into car (make, model, price) values ('GMC', 'Sonoma Club Coupe', 14965.73);
insert into car (make, model, price) values ('Ford', 'Th!nk', 88329.45);
insert into car (make, model, price) values ('Dodge', 'Dakota', 51233.66);
insert into car (make, model, price) values ('Nissan', 'Cube', 17423.31);
insert into car (make, model, price) values ('Dodge', 'Viper', 35135.81);
insert into car (make, model, price) values ('Pontiac', 'Aztek', 85332.62);
insert into car (make, model, price) values ('Toyota', 'TundraMax', 43745.10);
insert into car (make, model, price) values ('Dodge', 'Ram 3500', 61587.33);
insert into car (make, model, price) values ('Pontiac', 'Firefly', 88953.48);
insert into car (make, model, price) values ('Land Rover', 'Discovery', 69859.98);
insert into car (make, model, price) values ('Mitsubishi', '3000GT', 53033.95);
insert into car (make, model, price) values ('GMC', 'Savana 1500', 56810.38);
insert into car (make, model, price) values ('Toyota', 'Corolla', 42962.12);
insert into car (make, model, price) values ('Toyota', '4Runner', 84545.87);
insert into car (make, model, price) values ('Pontiac', 'Sunbird', 46445.69);
insert into car (make, model, price) values ('Mercedes-Benz', 'CLS-Class', 32120.77);
insert into car (make, model, price) values ('Aston Martin', 'V8 Vantage', 86678.03);
insert into car (make, model, price) values ('Maserati', 'Quattroporte', 76065.18);
insert into car (make, model, price) values ('Chrysler', 'Town & Country', 28484.58);
insert into car (make, model, price) values ('Subaru', 'Forester', 85794.39);
insert into car (make, model, price) values ('Lexus', 'GS', 79012.18);
insert into car (make, model, price) values ('Honda', 'Accord', 21303.92);
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', 45499.29);
insert into car (make, model, price) values ('Chevrolet', 'Silverado 1500', 28883.01);
insert into car (make, model, price) values ('Nissan', 'Frontier', 18693.60);
insert into car (make, model, price) values ('GMC', 'Envoy', 31787.77);
insert into car (make, model, price) values ('Lotus', 'Evora', 80637.68);
insert into car (make, model, price) values ('Volkswagen', 'CC', 83291.48);
insert into car (make, model, price) values ('Maserati', 'Spyder', 99264.50);
insert into car (make, model, price) values ('Pontiac', 'Trans Sport', 39204.45);
insert into car (make, model, price) values ('Dodge', 'Ram Van 3500', 88900.46);
insert into car (make, model, price) values ('GMC', 'Yukon', 10607.51);
insert into car (make, model, price) values ('Cadillac', 'CTS', 44103.78);
insert into car (make, model, price) values ('Lincoln', 'Continental', 86098.06);
insert into car (make, model, price) values ('Suzuki', 'Grand Vitara', 29262.64);
insert into car (make, model, price) values ('Buick', 'Regal', 98691.49);
insert into car (make, model, price) values ('Nissan', 'Sentra', 43603.50);
insert into car (make, model, price) values ('Chrysler', 'LHS', 99382.58);
insert into car (make, model, price) values ('Eagle', 'Vision', 26833.59);
insert into car (make, model, price) values ('Isuzu', 'Hombre', 31590.46);
insert into car (make, model, price) values ('Pontiac', 'Parisienne', 78605.30);
insert into car (make, model, price) values ('Ferrari', '612 Scaglietti', 30779.44);
insert into car (make, model, price) values ('Audi', 'S4', 54496.68);
insert into car (make, model, price) values ('Chevrolet', 'Monte Carlo', 57663.45);
insert into car (make, model, price) values ('Ford', 'Taurus', 57662.12);
insert into car (make, model, price) values ('Audi', 'A4', 11062.06);
insert into car (make, model, price) values ('Aston Martin', 'V8 Vantage', 38408.95);
insert into car (make, model, price) values ('Studebaker', 'Avanti', 76832.87);
insert into car (make, model, price) values ('GMC', 'Sierra 2500', 83187.47);
insert into car (make, model, price) values ('Mitsubishi', 'Challenger', 14413.99);
insert into car (make, model, price) values ('Honda', 'Accord', 95757.25);
insert into car (make, model, price) values ('Nissan', '300ZX', 70146.13);
insert into car (make, model, price) values ('Lincoln', 'MKX', 61817.31);
insert into car (make, model, price) values ('Ram', '2500', 73127.29);
insert into car (make, model, price) values ('Ford', 'Mustang', 72896.55);
insert into car (make, model, price) values ('GMC', 'Suburban 2500', 88455.09);
insert into car (make, model, price) values ('Subaru', 'Forester', 74203.84);
insert into car (make, model, price) values ('Saturn', 'Ion', 50298.50);
insert into car (make, model, price) values ('Aptera', 'Typ-1', 15844.66);
insert into car (make, model, price) values ('Pontiac', 'Trans Sport', 92132.57);
insert into car (make, model, price) values ('Honda', 'Civic', 22123.41);
insert into car (make, model, price) values ('Toyota', 'Solara', 80911.91);
insert into car (make, model, price) values ('Infiniti', 'G', 45863.14);
insert into car (make, model, price) values ('Volkswagen', 'Passat', 24755.23);
insert into car (make, model, price) values ('Volkswagen', 'Golf', 83061.75);
insert into car (make, model, price) values ('Toyota', 'Avalon', 65621.18);
insert into car (make, model, price) values ('Lincoln', 'Navigator', 28030.74);
insert into car (make, model, price) values ('GMC', 'Rally Wagon 3500', 81634.80);
insert into car (make, model, price) values ('Cadillac', 'Seville', 22619.71);
insert into car (make, model, price) values ('Mercedes-Benz', 'W123', 38836.97);
insert into car (make, model, price) values ('Nissan', 'Pathfinder', 97127.91);
insert into car (make, model, price) values ('Lotus', 'Elise', 28006.02);
insert into car (make, model, price) values ('Chevrolet', 'Corvette', 36945.11);
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', 95526.42);
insert into car (make, model, price) values ('Lexus', 'ES', 30598.95);
insert into car (make, model, price) values ('Dodge', 'Stratus', 92190.68);
insert into car (make, model, price) values ('BMW', 'X5', 75849.64);
insert into car (make, model, price) values ('Chevrolet', 'Camaro', 29086.46);
insert into car (make, model, price) values ('Toyota', 'MR2', 56526.01);
insert into car (make, model, price) values ('Saab', '9-5', 40115.98);
insert into car (make, model, price) values ('Volvo', 'C70', 91643.30);
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', 98174.57);
insert into car (make, model, price) values ('Ford', 'Transit Connect', 67730.08);
insert into car (make, model, price) values ('MINI', 'Countryman', 71582.25);
insert into car (make, model, price) values ('Ford', 'Windstar', 82756.46);
insert into car (make, model, price) values ('Pontiac', 'Montana', 29428.84);
insert into car (make, model, price) values ('GMC', 'Jimmy', 50341.52);
insert into car (make, model, price) values ('Hyundai', 'Sonata', 60993.89);
insert into car (make, model, price) values ('Mazda', '626', 44733.71);
insert into car (make, model, price) values ('Toyota', 'Tacoma', 50850.48);
insert into car (make, model, price) values ('Chrysler', 'Cirrus', 94651.14);
insert into car (make, model, price) values ('Hyundai', 'Santa Fe', 35006.14);
insert into car (make, model, price) values ('Saturn', 'Astra', 82860.06);
insert into car (make, model, price) values ('Pontiac', 'Solstice', 11044.97);
insert into car (make, model, price) values ('Suzuki', 'XL-7', 79187.23);
insert into car (make, model, price) values ('Ford', 'Mustang', 69047.06);
insert into car (make, model, price) values ('GMC', 'Rally Wagon G3500', 49974.97);
insert into car (make, model, price) values ('Nissan', 'Altima', 93079.60);
insert into car (make, model, price) values ('Chevrolet', 'Colorado', 51594.02);
insert into car (make, model, price) values ('Pontiac', 'G3', 34968.23);
insert into car (make, model, price) values ('Kia', 'Sedona', 48028.72);
insert into car (make, model, price) values ('Lincoln', 'Town Car', 81647.25);
insert into car (make, model, price) values ('Buick', 'Skyhawk', 23938.97);
insert into car (make, model, price) values ('BMW', '7 Series', 60842.28);
insert into car (make, model, price) values ('Honda', 'Odyssey', 59764.02);
insert into car (make, model, price) values ('Pontiac', 'Tempest', 25177.07);
insert into car (make, model, price) values ('Volkswagen', 'Passat', 23185.13);
insert into car (make, model, price) values ('Maserati', 'Gran Sport', 20528.32);
insert into car (make, model, price) values ('BMW', 'X3', 45277.97);
insert into car (make, model, price) values ('Mazda', 'Mazda5', 25908.23);
insert into car (make, model, price) values ('Honda', 'Prelude', 54684.74);
insert into car (make, model, price) values ('Mercedes-Benz', 'SLK-Class', 26854.96);
insert into car (make, model, price) values ('Buick', 'Special', 99487.85);
insert into car (make, model, price) values ('Mazda', 'B-Series', 40403.82);
insert into car (make, model, price) values ('Nissan', 'Cube', 38410.49);
insert into car (make, model, price) values ('Honda', 'S2000', 79658.36);
insert into car (make, model, price) values ('Mitsubishi', 'Eclipse', 35501.85);
insert into car (make, model, price) values ('Daewoo', 'Nubira', 61392.63);
insert into car (make, model, price) values ('Chevrolet', 'Impala', 10544.22);
insert into car (make, model, price) values ('BMW', '545', 95915.61);
insert into car (make, model, price) values ('BMW', '3 Series', 11309.35);
insert into car (make, model, price) values ('Mercedes-Benz', 'M-Class', 31448.54);
insert into car (make, model, price) values ('Lincoln', 'MKX', 42712.51);
insert into car (make, model, price) values ('Nissan', 'Murano', 39224.98);
insert into car (make, model, price) values ('BMW', 'Z8', 57779.67);
insert into car (make, model, price) values ('Mercury', 'Monterey', 19398.71);
insert into car (make, model, price) values ('Kia', 'Sportage', 60531.32);
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', 54117.07);
insert into car (make, model, price) values ('Chevrolet', '3500', 54395.76);
insert into car (make, model, price) values ('Buick', 'Park Avenue', 12057.77);
insert into car (make, model, price) values ('Audi', 'Coupe GT', 98636.11);
insert into car (make, model, price) values ('Ford', 'GT500', 49189.47);
insert into car (make, model, price) values ('Mazda', 'Familia', 23164.91);
insert into car (make, model, price) values ('Ford', 'Econoline E350', 26562.56);
insert into car (make, model, price) values ('Chevrolet', 'Express 2500', 60551.43);
insert into car (make, model, price) values ('Chrysler', '300M', 76899.51);
insert into car (make, model, price) values ('Isuzu', 'VehiCROSS', 89912.41);
insert into car (make, model, price) values ('Oldsmobile', 'Bravada', 95690.56);
insert into car (make, model, price) values ('Isuzu', 'Ascender', 68585.86);
insert into car (make, model, price) values ('Chevrolet', 'Express 3500', 31229.20);
insert into car (make, model, price) values ('Cadillac', 'XLR-V', 20229.12);
insert into car (make, model, price) values ('Audi', 'Cabriolet', 11630.65);
insert into car (make, model, price) values ('Lamborghini', 'Gallardo', 45783.92);
insert into car (make, model, price) values ('Chevrolet', 'Cavalier', 62858.66);
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', 47244.75);
insert into car (make, model, price) values ('Mitsubishi', 'Raider', 69693.98);
insert into car (make, model, price) values ('Suzuki', 'Sidekick', 93096.71);
insert into car (make, model, price) values ('Dodge', 'Ram Van 3500', 72549.93);
insert into car (make, model, price) values ('Ford', 'Econoline E150', 18835.50);
insert into car (make, model, price) values ('Scion', 'tC', 47471.46);
insert into car (make, model, price) values ('Mercedes-Benz', 'CLK-Class', 69602.95);
insert into car (make, model, price) values ('Lincoln', 'MKX', 18386.49);
insert into car (make, model, price) values ('Ford', 'F450', 78402.54);
insert into car (make, model, price) values ('Ford', 'Expedition', 16590.74);
insert into car (make, model, price) values ('Chevrolet', 'Express 3500', 63167.07);
insert into car (make, model, price) values ('Mitsubishi', 'Galant', 81227.39);
insert into car (make, model, price) values ('Ram', '1500', 84064.84);
insert into car (make, model, price) values ('Subaru', 'Legacy', 26841.57);
insert into car (make, model, price) values ('Chevrolet', 'Express 3500', 92377.86);
insert into car (make, model, price) values ('Chevrolet', 'Impala', 75311.37);
insert into car (make, model, price) values ('Suzuki', 'SJ 410', 15846.33);
insert into car (make, model, price) values ('Ford', 'Explorer Sport Trac', 39069.88);
insert into car (make, model, price) values ('Mitsubishi', 'Eclipse', 41963.23);
insert into car (make, model, price) values ('Ford', 'E-350 Super Duty Van', 31461.44);
insert into car (make, model, price) values ('Ford', 'Windstar', 88228.54);
insert into car (make, model, price) values ('Ford', 'Explorer Sport', 80820.31);
insert into car (make, model, price) values ('Mercury', 'Tracer', 79829.19);
insert into car (make, model, price) values ('Audi', 'riolet', 63445.73);
insert into car (make, model, price) values ('Mitsubishi', 'Sigma', 72578.08);
insert into car (make, model, price) values ('Volvo', 'C30', 41582.75);
insert into car (make, model, price) values ('Jeep', 'Cherokee', 40463.30);
insert into car (make, model, price) values ('Kia', 'Sportage', 11841.81);
insert into car (make, model, price) values ('Porsche', 'Cayenne', 33237.14);
insert into car (make, model, price) values ('Chevrolet', 'Malibu', 65071.00);
insert into car (make, model, price) values ('Chevrolet', 'Express', 66896.25);
insert into car (make, model, price) values ('Chevrolet', 'Monte Carlo', 64541.97);
insert into car (make, model, price) values ('Oldsmobile', 'Cutlass', 85367.26);
insert into car (make, model, price) values ('Buick', 'Lucerne', 77435.17);
insert into car (make, model, price) values ('BMW', '600', 68878.17);
insert into car (make, model, price) values ('Chevrolet', 'Caprice', 78020.92);
insert into car (make, model, price) values ('Hyundai', 'Sonata', 12179.92);
insert into car (make, model, price) values ('Suzuki', 'SX4', 86907.51);
insert into car (make, model, price) values ('Toyota', 'Celica', 51808.52);
insert into car (make, model, price) values ('Infiniti', 'QX', 64386.68);
insert into car (make, model, price) values ('Mitsubishi', 'Precis', 54728.80);
insert into car (make, model, price) values ('BMW', 'Z3', 96516.74);
insert into car (make, model, price) values ('Lamborghini', 'Diablo', 22887.63);
insert into car (make, model, price) values ('Chevrolet', 'Silverado 2500', 69497.17);
insert into car (make, model, price) values ('Audi', 'S5', 69761.88);
insert into car (make, model, price) values ('Chevrolet', 'Tahoe', 66396.46);
insert into car (make, model, price) values ('GMC', 'Sierra 3500', 44855.74);
insert into car (make, model, price) values ('Audi', 'riolet', 36151.01);
insert into car (make, model, price) values ('GMC', 'Savana 3500', 63758.39);
insert into car (make, model, price) values ('Chrysler', 'Sebring', 15593.83);
insert into car (make, model, price) values ('Kia', 'Rio', 96622.29);
insert into car (make, model, price) values ('GMC', '1500 Club Coupe', 96811.59);
insert into car (make, model, price) values ('Volvo', 'V90', 98418.78);
insert into car (make, model, price) values ('GMC', 'Savana 1500', 76328.70);
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', 82679.86);
insert into car (make, model, price) values ('Ford', 'Aerostar', 55453.82);
insert into car (make, model, price) values ('Dodge', 'Ram 2500 Club', 24947.54);
insert into car (make, model, price) values ('Nissan', 'Pathfinder', 18448.44);
insert into car (make, model, price) values ('Porsche', '911', 96650.94);
insert into car (make, model, price) values ('Chevrolet', 'Silverado', 64633.64);
insert into car (make, model, price) values ('MINI', 'Clubman', 50036.96);
insert into car (make, model, price) values ('Ford', 'Tempo', 49843.19);
insert into car (make, model, price) values ('Buick', 'LeSabre', 43125.27);
insert into car (make, model, price) values ('Buick', 'LeSabre', 21354.25);
insert into car (make, model, price) values ('Cadillac', 'Escalade', 53958.81);
insert into car (make, model, price) values ('Infiniti', 'QX', 35666.08);
insert into car (make, model, price) values ('BMW', '5 Series', 84015.74);
insert into car (make, model, price) values ('GMC', 'Sierra 1500', 14176.52);
insert into car (make, model, price) values ('Volvo', 'S80', 96813.38);
insert into car (make, model, price) values ('Jaguar', 'X-Type', 99846.74);
insert into car (make, model, price) values ('Buick', 'LeSabre', 85947.71);
insert into car (make, model, price) values ('Acura', 'ZDX', 17006.64);
insert into car (make, model, price) values ('Volkswagen', 'GTI', 28905.67);
insert into car (make, model, price) values ('Oldsmobile', 'LSS', 43087.05);
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', 79441.98);
insert into car (make, model, price) values ('Dodge', 'Ram', 89478.86);
insert into car (make, model, price) values ('Ferrari', '612 Scaglietti', 45069.15);
insert into car (make, model, price) values ('Suzuki', 'Grand Vitara', 26158.93);
insert into car (make, model, price) values ('Mitsubishi', 'Lancer Evolution', 59871.03);
insert into car (make, model, price) values ('Ford', 'F150', 87782.64);
insert into car (make, model, price) values ('Volkswagen', 'Golf', 93180.94);
insert into car (make, model, price) values ('Mercury', 'Sable', 36322.35);
insert into car (make, model, price) values ('Subaru', 'Outback', 32216.19);
insert into car (make, model, price) values ('Toyota', 'Tacoma', 47673.64);
insert into car (make, model, price) values ('Pontiac', 'Solstice', 69264.86);
insert into car (make, model, price) values ('Acura', 'TL', 56605.21);
insert into car (make, model, price) values ('Lexus', 'LS', 54516.44);
insert into car (make, model, price) values ('Chevrolet', 'Corvette', 73444.46);
insert into car (make, model, price) values ('Hyundai', 'Santa Fe', 73284.26);
insert into car (make, model, price) values ('Toyota', 'Tacoma', 77527.61);
insert into car (make, model, price) values ('GMC', 'Savana 1500', 36063.08);
insert into car (make, model, price) values ('Cadillac', 'Fleetwood', 11514.40);
insert into car (make, model, price) values ('Dodge', 'Charger', 21369.27);
insert into car (make, model, price) values ('Volvo', 'S80', 41465.06);
insert into car (make, model, price) values ('Toyota', 'Prius', 31615.32);
insert into car (make, model, price) values ('Lexus', 'LS', 94093.29);
insert into car (make, model, price) values ('Toyota', 'Sienna', 25844.82);
insert into car (make, model, price) values ('BMW', '3 Series', 18233.41);
insert into car (make, model, price) values ('Plymouth', 'Voyager', 16343.79);
insert into car (make, model, price) values ('Mercedes-Benz', '300TE', 79081.68);
insert into car (make, model, price) values ('Chrysler', 'Crossfire Roadster', 80440.82);
insert into car (make, model, price) values ('Volkswagen', 'Fox', 73262.18);
insert into car (make, model, price) values ('Ford', 'E-Series', 29294.81);
insert into car (make, model, price) values ('Mitsubishi', 'Galant', 13138.19);
insert into car (make, model, price) values ('Land Rover', 'Range Rover', 90573.25);
insert into car (make, model, price) values ('Hyundai', 'Elantra', 18745.26);
insert into car (make, model, price) values ('Toyota', 'Tacoma Xtra', 50493.35);
insert into car (make, model, price) values ('Scion', 'tC', 15698.97);
insert into car (make, model, price) values ('Chevrolet', 'Cavalier', 51751.28);
insert into car (make, model, price) values ('Chevrolet', 'Sportvan G30', 26523.84);
insert into car (make, model, price) values ('GMC', 'Sierra 1500', 43992.55);
insert into car (make, model, price) values ('Dodge', 'Neon', 61925.23);
insert into car (make, model, price) values ('Pontiac', 'GTO', 60628.82);
insert into car (make, model, price) values ('Pontiac', 'Solstice', 68937.35);
insert into car (make, model, price) values ('Mitsubishi', 'Lancer Evolution', 65135.20);
insert into car (make, model, price) values ('Toyota', 'Corolla', 23560.37);
insert into car (make, model, price) values ('Dodge', 'Ram Van B150', 59255.29);
insert into car (make, model, price) values ('Toyota', 'Xtra', 22897.43);
insert into car (make, model, price) values ('Chevrolet', 'Malibu Maxx', 66710.49);
insert into car (make, model, price) values ('Hyundai', 'Santa Fe', 91428.08);
insert into car (make, model, price) values ('Toyota', 'Matrix', 16670.84);
insert into car (make, model, price) values ('Buick', 'Estate', 59454.42);
insert into car (make, model, price) values ('Acura', 'RDX', 32816.21);
insert into car (make, model, price) values ('Oldsmobile', 'LSS', 88843.00);
insert into car (make, model, price) values ('Dodge', 'Stratus', 26338.12);
insert into car (make, model, price) values ('Mitsubishi', 'Eclipse', 68494.26);
insert into car (make, model, price) values ('Saab', '9-5', 11257.04);
insert into car (make, model, price) values ('Ford', 'Taurus', 59822.15);
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', 71469.82);
insert into car (make, model, price) values ('Pontiac', '6000', 29011.12);
insert into car (make, model, price) values ('Nissan', 'Leaf', 96156.56);
insert into car (make, model, price) values ('Mercury', 'Mariner', 71351.33);
insert into car (make, model, price) values ('Volvo', 'V70', 83089.79);
insert into car (make, model, price) values ('Chevrolet', 'Astro', 27952.99);
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', 47185.86);
insert into car (make, model, price) values ('Buick', 'Enclave', 86652.34);
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', 70523.97);
insert into car (make, model, price) values ('Honda', 'Passport', 59407.15);
insert into car (make, model, price) values ('BMW', '5 Series', 33803.13);
insert into car (make, model, price) values ('Audi', 'S4', 44424.42);
insert into car (make, model, price) values ('Dodge', 'Ram 3500', 56951.58);
insert into car (make, model, price) values ('Ford', 'Mustang', 54543.14);
insert into car (make, model, price) values ('Pontiac', 'Aztek', 14582.75);
insert into car (make, model, price) values ('BMW', 'Z3', 56173.37);
insert into car (make, model, price) values ('Lincoln', 'Town Car', 15871.42);
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', 97572.82);
insert into car (make, model, price) values ('Mercedes-Benz', 'G-Class', 14427.28);
insert into car (make, model, price) values ('Volkswagen', 'Jetta III', 37734.27);
insert into car (make, model, price) values ('GMC', '2500 Club Coupe', 23403.63);
insert into car (make, model, price) values ('Lotus', 'Esprit', 30214.52);
insert into car (make, model, price) values ('Toyota', 'Camry Solara', 69386.95);
insert into car (make, model, price) values ('Nissan', 'Quest', 98534.14);
insert into car (make, model, price) values ('Cadillac', 'Escalade EXT', 79785.27);
insert into car (make, model, price) values ('Bentley', 'Arnage', 92167.80);
insert into car (make, model, price) values ('Lincoln', 'Blackwood', 19723.40);
insert into car (make, model, price) values ('Ford', 'Flex', 96350.66);
insert into car (make, model, price) values ('BMW', '745', 50880.19);
insert into car (make, model, price) values ('Mitsubishi', 'Montero', 27983.53);
insert into car (make, model, price) values ('Audi', 'A4', 89163.47);
insert into car (make, model, price) values ('Ferrari', '430 Scuderia', 16194.65);
insert into car (make, model, price) values ('Suzuki', 'Daewoo Lacetti', 58865.65);
insert into car (make, model, price) values ('Volkswagen', 'Fox', 20589.81);
insert into car (make, model, price) values ('Pontiac', '6000', 25363.25);
insert into car (make, model, price) values ('Mazda', 'MPV', 81577.35);
insert into car (make, model, price) values ('Lexus', 'ES', 92587.22);
insert into car (make, model, price) values ('Land Rover', 'Discovery', 91880.32);
insert into car (make, model, price) values ('GMC', 'Canyon', 63550.55);
insert into car (make, model, price) values ('Chevrolet', 'G-Series G10', 85104.30);
insert into car (make, model, price) values ('Pontiac', 'Vibe', 75711.44);
insert into car (make, model, price) values ('Suzuki', 'Kizashi', 77207.40);
insert into car (make, model, price) values ('Subaru', 'Impreza', 84962.52);
insert into car (make, model, price) values ('Cadillac', 'Escalade EXT', 48328.39);
insert into car (make, model, price) values ('GMC', 'Yukon XL 1500', 29868.81);
insert into car (make, model, price) values ('BMW', '745', 72831.57);
insert into car (make, model, price) values ('GMC', 'Yukon', 42565.59);
insert into car (make, model, price) values ('Lexus', 'LX', 11350.92);
insert into car (make, model, price) values ('Bentley', 'Continental', 68035.78);
insert into car (make, model, price) values ('Subaru', 'XT', 24372.31);
insert into car (make, model, price) values ('GMC', 'Yukon XL 2500', 59971.27);
insert into car (make, model, price) values ('GMC', 'Yukon XL 2500', 87381.26);
insert into car (make, model, price) values ('Lincoln', 'Town Car', 81399.40);
insert into car (make, model, price) values ('Mercury', 'Mountaineer', 27801.05);
insert into car (make, model, price) values ('Oldsmobile', 'Alero', 80842.90);
insert into car (make, model, price) values ('Infiniti', 'QX', 95989.01);
insert into car (make, model, price) values ('Oldsmobile', 'Alero', 16580.58);
insert into car (make, model, price) values ('Chrysler', '300M', 69349.55);
insert into car (make, model, price) values ('Chevrolet', 'Silverado', 50507.72);
insert into car (make, model, price) values ('Land Rover', 'Range Rover', 12921.93);
insert into car (make, model, price) values ('Saab', '9000', 82818.85);
insert into car (make, model, price) values ('Dodge', 'Caravan', 24871.53);
insert into car (make, model, price) values ('Jaguar', 'S-Type', 51761.20);
insert into car (make, model, price) values ('BMW', 'Z4', 31060.33);
insert into car (make, model, price) values ('Chevrolet', 'Equinox', 22185.37);
insert into car (make, model, price) values ('Suzuki', 'Verona', 44708.25);
insert into car (make, model, price) values ('Toyota', 'Corolla', 49608.67);
insert into car (make, model, price) values ('Mazda', 'Tribute', 93990.53);
insert into car (make, model, price) values ('Acura', 'TL', 16822.47);
insert into car (make, model, price) values ('Toyota', 'Tacoma', 25566.03);
insert into car (make, model, price) values ('Maserati', '430', 83886.81);
insert into car (make, model, price) values ('Mazda', 'B-Series Plus', 10432.07);
insert into car (make, model, price) values ('Pontiac', 'Solstice', 21523.95);
insert into car (make, model, price) values ('Toyota', 'RAV4', 54324.92);
insert into car (make, model, price) values ('Lincoln', 'MKT', 72110.27);
insert into car (make, model, price) values ('GMC', 'Vandura 3500', 49497.21);
insert into car (make, model, price) values ('Toyota', 'Yaris', 42055.48);
insert into car (make, model, price) values ('Audi', 'A8', 60269.83);
insert into car (make, model, price) values ('Mercury', 'Sable', 23788.80);
insert into car (make, model, price) values ('Chevrolet', 'Monte Carlo', 66151.42);
insert into car (make, model, price) values ('Ford', 'Club Wagon', 18185.60);
insert into car (make, model, price) values ('Mazda', 'RX-8', 15092.74);
insert into car (make, model, price) values ('Mazda', 'CX-5', 81480.89);
insert into car (make, model, price) values ('Ford', 'Econoline E150', 17638.22);
insert into car (make, model, price) values ('Mercury', 'Cougar', 45601.38);
insert into car (make, model, price) values ('Chevrolet', 'Impala', 18960.29);
insert into car (make, model, price) values ('Hyundai', 'Tiburon', 84182.90);
insert into car (make, model, price) values ('Dodge', 'Viper', 66731.74);
insert into car (make, model, price) values ('Eagle', 'Talon', 31020.47);
insert into car (make, model, price) values ('Chrysler', 'Sebring', 34189.51);
insert into car (make, model, price) values ('Mazda', 'B-Series', 47326.56);
insert into car (make, model, price) values ('Mitsubishi', 'Galant', 22036.83);
insert into car (make, model, price) values ('Ford', 'F250', 95029.35);
insert into car (make, model, price) values ('Buick', 'Skyhawk', 68196.77);
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', 70225.26);
insert into car (make, model, price) values ('Lamborghini', 'Countach', 16306.93);
insert into car (make, model, price) values ('Chevrolet', 'Corvette', 83254.96);
insert into car (make, model, price) values ('Lotus', 'Elise', 21995.55);
insert into car (make, model, price) values ('Land Rover', 'LR2', 35708.92);
insert into car (make, model, price) values ('Jaguar', 'XJ Series', 75512.40);
insert into car (make, model, price) values ('Audi', 'S4', 34240.32);
insert into car (make, model, price) values ('Chevrolet', 'K5 Blazer', 62427.51);
insert into car (make, model, price) values ('Toyota', '4Runner', 40304.42);
insert into car (make, model, price) values ('Toyota', 'Tercel', 34561.18);
insert into car (make, model, price) values ('Volkswagen', 'Vanagon', 37755.58);
insert into car (make, model, price) values ('Kia', 'Sorento', 90132.60);
insert into car (make, model, price) values ('Audi', '90', 30881.30);
insert into car (make, model, price) values ('Mazda', 'B-Series', 64032.85);
insert into car (make, model, price) values ('Land Rover', 'Discovery Series II', 53860.39);
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', 47884.49);
insert into car (make, model, price) values ('Buick', 'Regal', 90470.11);
insert into car (make, model, price) values ('Daewoo', 'Leganza', 43600.55);
insert into car (make, model, price) values ('BMW', 'X3', 17287.95);
insert into car (make, model, price) values ('Dodge', 'Journey', 46690.40);
insert into car (make, model, price) values ('Foose', 'Hemisfear', 54454.27);
insert into car (make, model, price) values ('Isuzu', 'Trooper', 11379.20);
insert into car (make, model, price) values ('Pontiac', 'G6', 22947.99);
insert into car (make, model, price) values ('Mazda', 'Protege', 68185.68);
insert into car (make, model, price) values ('Nissan', 'Datsun/Nissan Z-car', 80456.47);
insert into car (make, model, price) values ('Acura', 'Legend', 13390.20);
insert into car (make, model, price) values ('Chrysler', 'Crossfire', 90443.06);
insert into car (make, model, price) values ('Isuzu', 'Ascender', 73573.82);
insert into car (make, model, price) values ('Pontiac', 'G5', 20982.93);
insert into car (make, model, price) values ('Infiniti', 'QX', 39710.66);
insert into car (make, model, price) values ('Nissan', 'Xterra', 93535.89);
insert into car (make, model, price) values ('Mitsubishi', 'Challenger', 48342.17);
insert into car (make, model, price) values ('Saab', '9-3', 42342.67);
insert into car (make, model, price) values ('Hyundai', 'Elantra', 46337.31);
insert into car (make, model, price) values ('Chevrolet', 'G-Series G20', 47285.94);
insert into car (make, model, price) values ('Chevrolet', 'Caprice Classic', 22792.71);
insert into car (make, model, price) values ('Ford', 'F250', 19496.79);
insert into car (make, model, price) values ('GMC', 'Savana 1500', 66064.09);
insert into car (make, model, price) values ('Dodge', 'Ram 1500 Club', 10006.69);
insert into car (make, model, price) values ('Mercedes-Benz', 'W201', 74263.01);
insert into car (make, model, price) values ('Volkswagen', 'Scirocco', 75983.75);
insert into car (make, model, price) values ('Oldsmobile', '98', 62613.76);
insert into car (make, model, price) values ('Ford', 'Expedition', 21137.71);
insert into car (make, model, price) values ('Chevrolet', 'Suburban 1500', 85020.89);
insert into car (make, model, price) values ('Cadillac', 'Fleetwood', 85328.59);
insert into car (make, model, price) values ('Mercury', 'Topaz', 93139.57);
insert into car (make, model, price) values ('Volkswagen', 'Touareg 2', 89648.69);
insert into car (make, model, price) values ('Ford', 'Club Wagon', 96457.32);
insert into car (make, model, price) values ('Dodge', 'Ram 2500 Club', 86696.36);
insert into car (make, model, price) values ('Mercury', 'Mountaineer', 38709.78);
insert into car (make, model, price) values ('Buick', 'LaCrosse', 61119.04);
insert into car (make, model, price) values ('Volkswagen', 'New Beetle', 57394.74);
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', 25409.92);
insert into car (make, model, price) values ('Geo', 'Metro', 77666.18);
insert into car (make, model, price) values ('Honda', 'Fit', 61034.46);
insert into car (make, model, price) values ('Pontiac', 'GTO', 34357.39);
insert into car (make, model, price) values ('Toyota', 'Camry Solara', 94917.69);
insert into car (make, model, price) values ('Chevrolet', 'Caprice', 67089.74);
insert into car (make, model, price) values ('Nissan', 'Maxima', 57540.56);
insert into car (make, model, price) values ('Subaru', 'Impreza', 77175.79);
insert into car (make, model, price) values ('Toyota', 'MR2', 97773.38);
insert into car (make, model, price) values ('Audi', 'S4', 55523.49);
insert into car (make, model, price) values ('Lincoln', 'Continental Mark VII', 62889.39);
insert into car (make, model, price) values ('Saturn', 'S-Series', 39895.47);
insert into car (make, model, price) values ('Subaru', 'Leone', 61288.43);
insert into car (make, model, price) values ('Toyota', 'Yaris', 47661.42);
insert into car (make, model, price) values ('Maserati', 'Quattroporte', 37234.88);
insert into car (make, model, price) values ('Nissan', 'JUKE', 14779.66);
insert into car (make, model, price) values ('Kia', 'Sportage', 21576.20);
insert into car (make, model, price) values ('Toyota', 'Xtra', 68716.44);
insert into car (make, model, price) values ('Nissan', '200SX', 16694.75);
insert into car (make, model, price) values ('Lexus', 'ES', 31809.11);
insert into car (make, model, price) values ('BMW', 'Z4 M', 51227.22);
insert into car (make, model, price) values ('Ford', 'F-Series Super Duty', 57595.80);
